README.md
cra-tf-validate-ignore-rules.json
examples/complete/README.md
examples/complete/main.tf
main.tf
module-metadata.json
variables.tf

Added CBR support
***https://github.ibm.com/GoldenEye/issues/issues/4833***
Run the CI pipeline when the PR is ready for …

feat: added cbr support

---

README.md

status update
Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR …

docs: status update

---

README.md
examples/basic/version.tf
examples/complete/version.tf
examples/fscloud/version.tf
module-metadata.json
profiles/fscloud/README.md
profiles/fscloud/version.tf
version.tf

Bump provider version to pick up bug fix for auth policies in 1.54.0
Update IBM provider to v1.54.0
```
/run pipeline
```
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of …

fix: upgrade provider to 1.54.0

---

main.tf
module-metadata.json
tests/pr_test.go

Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies. If there is a Git issue for the change, please link to it.
https://github.com/terraform-ibm-modules/terraform-ibm-issue-tracker/issues/62
Your notes help the merger write the commit message for the PR that is …

fix: validate kms encryption by plan

---

README.md
examples/complete/README.md
examples/complete/main.tf
main.tf

Fixed bug in KMS validation logic and unused CBR code from complete example.
Run the CI pipeline when the PR is ready …

fix: fixed bug in KMS validation logic

---

cra-tf-validate-ignore-rules.json
main.tf
profiles/fscloud/README.md

Fixed the typo for service_endpoints
Run the CI pipeline when the PR is ready for review and you expect tests to pass. …

fix: fixed typo and removed the ignore file entry

---

cra-tf-validate-ignore-rules.json
main.tf

ES encryption fix and service-endpoint.
https://github.ibm.com/goldeneye/issues/issues/5142
Run the CI pipeline when the …

fix: fixed ES encryption and service-endpoint

---

.github/workflows/ci.yml
cra-config.yaml

Update ci.yml and cra-config.yaml

---

.github/settings.yml

add missing topics

---

examples/complete/README.md

update complete example readme

---

ibm_catalog.json

fix: architecture link for catalog offering

---

ibm_catalog.json

fix: required permissions for Event Streams solution

---

.github/settings.yml

Add "deployable-architecture" topic

---

cra-config.yaml
ibm_catalog.json

update to fscloud profile 1.6.0

---

solutions/standard/DA-schemas-topics-cbr.md

@akocbek 
I've updated some basic things in this PR to your PR (simplify heading structure, remove CBR abbreviation [isn't approved], updated capitalization...)
What's needed is some lead-in or context info under each heading and perhaps a different way of showing the options. Take a look at [Configuring keys in a KMS in IBM Cloud projects](https://github.com/terraform-ibm-modules/terraform-ibm-kms-all-inclusive/blob/main/solutions/standard/DA-keys.md) for what I think is a similar topic that shows options and examples. 
```
/run …
```

editorial updates

---

README.md
examples/basic/version.tf
examples/complete/main.tf
examples/complete/version.tf
main.tf
modules/fscloud/README.md
modules/fscloud/version.tf
version.tf

Updated ibm provider version to support cbr module
```
/run pipeline
```

fix: update ibm provider version to support cbr module

---

README.md
examples/basic/outputs.tf
examples/complete/outputs.tf
modules/fscloud/README.md
modules/fscloud/outputs.tf
outputs.tf
solutions/quickstart/outputs.tf

add a new `kafka_broker_version` as output to the module. Also Update examples and Readme
```
/run pipeline
```

feat: add kafka_broker_version output

---

tests/pr_test.go

Event Streams team have allowlisted the goldenEye dev account (`abac0df06b644a9cabc6e44f55b3880e`) to be able to provision enterprise plan instance concurrently in regions `us-south` `us-east` `ca-tor` `br-sao` `au-syd` `jp-tok` `jp-osa` `eu-de` `eu-es` `eu-gb`.
This means we can now unskip the `TestFSCloudInSchematics` test
```
/run pipeline
```
- Include information that users …

tests: re-enable TestFSCloudInSchematics

---

ibm_catalog.json

update AT, SCC and SM dependency versions

---

variables.tf

Updated the validation to allow deployment in the region `eu-fr2` for the plan 'enterprise-3nodes-2tb'
This PR updates the validation to allow deployment in the region eu-fr2 for the plan 'enterprise-3nodes-2tb'
```
/run pipeline
```
- …

fix: updated validation to allow deployment in the eu-fr2 region
